# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='24dff91e-7fc7-484d-8967-9bf456ef8720', max_length=255),
        ),
    ]
